[build-system]
requires = ["setuptools>=45", "wheel", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "power_svd"
version = "0.1.0"
description = "Power method SVD implementation in C++"
requires-python = ">=3.6"
dependencies = ["numpy>=1.19.0"]